sonar.projectKey=DSLZL_CLSP
sonar.organization=lzl2891362919


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=CLSP
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.rust.clippy.enabled=false
sonar.rust.clippyReport.reportPaths=clippy-report.json
sonar.exclusions=clippy-report.json
